### ISSUE TITLE
Adaptar os Benchmarks em Python

### ISSUE THREAD

**Issue by LeoFuso** [LeoFuso/edcalc#14]
Adaptar os `Benchmarks` em `Python` para funcionar com os novos métodos implementados de medida de distância

**Comment by LeoFuso** [comment]
[Problemas com Memory Leak](https://stackoverflow.com/questions/5508904/c-extension-in-python-return-py-buildvalue-memory-leak-problem)

**Comment by LeoFuso** [comment]
Para a versão _128_:
 - Todos os três métodos funcionam como esperado

Para a versão _256_:
- Euclidean e Manhattan funcionam, mas não juntos. Isto é, se eu realizo uma chamada para o Euclidean e posteriormente eu realizo uma chamada para o Manhattan, a segunda chamada causa um _segment fault_, e vice versa.

Cosine não parece funcionar em nenhum dos casos.

Caso eu queria executar Euclidean e posteriormente executar Manhattan, eu preciso remover a pasta gerada pelo _Pyton_ `  __pycache__ `
Eu não posso realizar duas chamadas para a API sequenciais, sem antes precisar apagar a pasta `  __pycache__ `
 Isso é verdade até mesmo para caso eu precise executar duas vezes o método Manhattan, por exemplo.



São notas sobre a integração, a implementação destas funcionalidades em __C++__ está funcionando perfeitamente.

**Comment by mvrozanti** [comment]
>a implementação destas funcionalidades em C++ está funcionando perfeitamente.

O resultado da função cosseno para AVX256 com os seguintes parâmetros _não_ está dando 0
```
double p[] = {1,2,3,4,5,6,7,8};
double q[] = {1,2,3,4,5,6,7,8};
```

Será que estou chamando errado?
